### ISSUE TITLE
keyboard layout cannot see clearly in apps with dark theme

### ISSUE THREAD

**Issue by liziqiang** [freefelt/YouType#1]
keyboard layout cannot see clearly in apps with dark theme. Like iterm2，vscode

**Comment by freefelt** [comment]
Hi! Can you please, show a screenshot?

**Comment by liziqiang** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/208130/160796090-d0222a04-c22e-43b8-a0a2-8805a7dec16c.png">

**Comment by freefelt** [comment]
Transfered it to common issue #3
