### ISSUE TITLE
“YouType.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by alfuken** [freefelt/YouType#11]
> “YouType.app” can’t be opened because Apple cannot check it for malicious software.
> This software needs to be updated. Contact the developer for more information.
> Safari downloaded this file today at 11:37.

Would be nice to have this dealt with. ;)

**Comment by freefelt** [comment]
Hi! Apple just wants me to pay them $100 a year. To open the application, you can right-click on the application icon and select Open, and then click Open in the pop-up window. This only needs to be done once.

**Comment by alfuken** [comment]
Fair enough. Would be nice to see that in the readme though. ;)
