### ISSUE TITLE
input language is not displayed in the address bar Safari

### ISSUE THREAD

**Issue by 5e3ru4o** [freefelt/YouType#12]
Hi! In Safari, the icon with the input language is not displayed in the address bar. Mac OS 12.5.1 (21G83). Safari 15.6.1 (17613.3.9.1.16)

![Снимок экрана 2022-09-05 в 21 02 51](https://user-images.githubusercontent.com/46959249/188498447-3bc70d58-2f55-43bd-9f16-8d03d7c354f0.jpg)

**Comment by freefelt** [comment]
Hi! Thanks for the feedback!
Unfortunately, I can't reproduce this behavior. Please keep in mind that the indicator is only displayed next to the ibeam cursor.
