### ISSUE TITLE
Brew Cask support

### ISSUE THREAD

**Issue by denis-g** [freefelt/YouType#13]
Привет,
Как насчет того чтобы добавить поддержку [brew cask](https://github.com/Homebrew/homebrew-cask) для быстрой установки и обновления ?

**Comment by freefelt** [comment]
Привет! Спасибо за предложение. Скорее всего добавлю, но это может быть не скоро. Сейчас в планах несколько интересных фич, а времени совсем нет, к сожалению.

**Comment by freefelt** [comment]
Добавил в список себе

**Comment by freefelt** [comment]
Готово! https://github.com/Homebrew/homebrew-cask/blob/master/Casks/youtype.rb
