### ISSUE TITLE
Hey! How to get the menubar icon back?

### ISSUE THREAD

**Issue by reznik** [freefelt/YouType#14]
So, I've hidden it but have no clue how to get it back. Please help.

**Comment by freefelt** [comment]
Hi! Just open the app from Launchpad again, and the icon will appear in menu before you click anywhere else. So you will be able to change the icon settings.

**Comment by reznik** [comment]
Hey, thanks for the response. Yes, the icon shows back after 5th launch (or so) but I can't catch it coz it disappears right when I try to click on it. So I simply cannot access the settings.

**Comment by freefelt** [comment]
Please, try to run the command "rm ~/Library/Preferences/com.AVKorotkov.YouType.plist" in Terminal and reboot your mac

**Comment by freefelt** [comment]
@reznik Hello! Have you managed to solve this problem?
