### ISSUE TITLE
German flag is gone

### ISSUE THREAD

**Issue by swayhead** [freefelt/YouType#15]
Hi,
I have 4 languages installed: German, Spanish, Italian and Russian.
It happens only with the German flag that after the first language change it goes away and looks like this:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/2189213/205449227-7b1a4f49-ff11-4854-a252-678985aa727a.png">
All other flags keep appearing as expected.
Any idea what's wrong?
Best
Leon

**Comment by swayhead** [comment]
Seems to be fixed now! Thank you 🙂

**Comment by freefelt** [comment]
Fixed in 0.7.2
