### ISSUE TITLE
Add formula to Homebrew

### ISSUE THREAD

**Issue by Zeebrah** [freefelt/YouType#16]
Love your app. Would be good to automate it with all the other open source software I use using Homebrew package manager. For that, there needs to be a formula of sort: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/bartender.rb

I found this manual: https://docs.brew.sh/Cask-Cookbook

I would be willing to help with that, but don't know for example details of uninstallation process.

Спасибо за чудесную программу, возвращает флер старой доброй Макоси!

**Comment by freefelt** [comment]
Thank you for the idea, but unfortunately, this is not possible at the moment. YouType does not pass the brew audit.
```
audit for youtype: failed
 - GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
Error: 1 problem in 1 cask detected
```
So we can only wait.

**Comment by freefelt** [comment]
Ready! https://github.com/Homebrew/homebrew-cask/blob/master/Casks/youtype.rb
