### ISSUE TITLE
не автозапускается на вентуре

### ISSUE THREAD

**Issue by Hentai-Princess** [freefelt/YouType#17]
галочка на автозапуск ставится, но при включении приложение не включается автоматически. В настройках в объектах входа YouType есть

**Comment by freefelt** [comment]
Странно, я такой проблемы не замечал и вроде она быть не должна. Приложение запускает сама система из списка объектов входа, а приложение только добавляется или удаляется оттуда.

Могу предположить, что YouType было запущено из другой папки, когда устанавливалась галочка автозапуска, а потом приложение было перенесено. Попробуйте удалить приложение из списка объектов входа вручную, а потом включить галочку из приложения.

**Comment by Hentai-Princess** [comment]
делала так, не помогло
до этого вообще в "объектах входа" YouType был без иконки. После удаления и добавления иконка не исчезает.
пока решила проблему не выключением компьютера, а просто погружением в спящий режим

**Comment by freefelt** [comment]
А если попробовать вручную добавить YouType в объекты входа через системные настройки, а не через приложение?

**Comment by Hentai-Princess** [comment]
а вот так сработало, спасибо большое
