### ISSUE TITLE
some suggestion for indicator.

### ISSUE THREAD

**Issue by eggthem17** [freefelt/YouType#2]
Hi, we meet here again.
I suggested indicator sync color with system dark mode at bitbucket.
Many days passes and I find some problem about it.

Many Software support dark mode sync with system default
but not all situation need that.
some times it must white background on keynote or powerpoint.
and many webpages needs own design.
so, I suggest indicator with outline!

![screenshot-2022-03-28-231416](https://user-images.githubusercontent.com/49383027/160417527-e56e9774-d9d2-4de1-bbd2-ac5c52e48547.png)

here's example.
it more clear to see with light background.

I hope it helps 'youtype' go further. :)

**Comment by freefelt** [comment]
Transfered it to common issue #3
