### ISSUE TITLE
missing flag for Greek

### ISSUE THREAD

**Issue by costispavlou** [freefelt/YouType#23]
any chance to add it? thanks in advance

**Comment by freefelt** [comment]
Hi! Thanks for the feedback. All the flags that are in YouType are taken from previous versions of macOS and the Greek layout did not have a flag. Unfortunately, I cannot take responsibility in front of all users which flag should be used. In a future update, customization of indicators will be added in the form of a paid feature. You will be able to choose any flag/image yourself.
