### ISSUE TITLE
Не работает настройка "Вернуть флаги"

### ISSUE THREAD

**Issue by mihdan** [freefelt/YouType#25]
<img width="354" alt="Снимок экрана 2023-03-23 в 01 03 13" src="https://user-images.githubusercontent.com/666732/227048766-3dac00b4-7286-4f62-8d4f-5c5dc3ffd4cb.png">

Вместо флагов показывает белое что-то. macOS Ventura 13.2.1. ОС перегружал, ставил и через brew и скриптами

**Comment by freefelt** [comment]
Привет! Довольно странно, на такой же конфигурации никак не могу повторить. А возле курсора так же отображается?

**Comment by mihdan** [comment]
Возле курсора тож чтот непонятное показывается

**Comment by freefelt** [comment]
Попробуйте эту сборку, пожалуйста. Если всплывет окно обновления, нажмите пропустить версию.
[YouType.app.zip](https://github.com/freefelt/YouType/files/11100881/YouType.app.zip)

**Comment by mihdan** [comment]
Спасибо, Александр, эта сборка работает. Флаги показываются и с курсором всё отлично
