### ISSUE TITLE
Флаги

### ISSUE THREAD

**Issue by regionerss** [freefelt/YouType#26]
Добрый день, установил на м2 Айр, на русском языке флаг отображается, на английском буква А! Можно исправить?
![IMG_3519](https://user-images.githubusercontent.com/115147005/232766003-9bc7497a-f5b8-4236-84ad-07cf9a4fb3e0.jpeg)
![IMG_3518](https://user-images.githubusercontent.com/115147005/232766039-9c333fe4-7b98-4b29-b75c-9e4248ab74c6.jpeg)

**Comment by freefelt** [comment]
Добрый день! "А" это не английская раскладка, а латинская. У нее нет флага. Вы можете заменить ее на "U.S." раскадку, тогда будет флаг.
![image](https://user-images.githubusercontent.com/9737848/233059500-1a0d170e-6651-460a-a305-39652a5ca49a.png)

![image](https://user-images.githubusercontent.com/9737848/233059423-89591cf0-9e58-4166-9a51-6ddc0868e251.png)
