### ISSUE TITLE
Не работает с кастомными иконками

### ISSUE THREAD

**Issue by yurastegny** [freefelt/YouType#31]
Александр, спасибо за приложение.

Очень хочется попробовать приложение в работе, но есть проблема. Я использую типографскую раскладку Бирмана. В ней установлены кастомные иконки раскладок. В Ютайпе одна иконка теряется, и для двух раскладок остаётся одна и та же. И даже если в приложении выбрать флаги — они не работают.

Понимаю, задача не приоритетная. Никогда не писал фидбек на Гитхабе, если что-то не так, прошу простить.
Раскладка Бирмана — https://ilyabirman.ru/typography-layout/

<img width="324" alt="Screenshot 2023-05-06 at 12 24 44" src="https://user-images.githubusercontent.com/72953443/236610705-47413be7-de46-4ed8-a48d-6d7e33bcb381.png">
<img width="340" alt="Screenshot 2023-05-06 at 12 24 33" src="https://user-images.githubusercontent.com/72953443/236610708-5697160a-b9a5-44af-b48b-5970e620fb90.png">

**Comment by freefelt** [comment]
Привет! Попробуйте почитать этот топик (https://github.com/freefelt/YouType/issues/18).
Там просто раскладка у него хитро настроена. Но можно и не хитро сделать)

**Comment by jt3k** [comment]
в том топике есть зип-архивы с программой. но похоже ни один из тех вариантов не работает. Может есть ещё воркараунд?
```
Air M1, macOS 13.4.1 22F82 arm64
```
