### ISSUE TITLE
Flags / icons for languages

### ISSUE THREAD

**Issue by grifoshPracticum** [freefelt/YouType#32]
Александр, здравствуйте!  
Пожалуйста, подскажите - почему могут не подтягиваться флаги на macOS? 
Версия OS: 13.3.1 (a) (22E772610a)

![Monosnap Monosnap Screenshot 2023-05-22 08-31-28(1) png 2023-05-22 09-15-06(1)](https://github.com/freefelt/YouType/assets/108690114/8cf050ef-3a8e-4ce2-90ec-a9f1bef7b909)

p.s. Искал адреса иконок в приложении, чтобы заменить все вручную, но не нашел, 
за то увидел, что статья review - [blog.skaplichniy.ru - Флажки](http://blog.skaplichniy.ru/all/flazhki/) - уже неактуальна =). 

---ENG---
Alexander, hi!
Please tell me - why flags cannot be raised on MacOS?
OS version: 13.3.1(a) (22E772610a)

Please, see the picture above.

p.s. I looked for the addresses of the icons in the application to replace everything manually, but did not find them,
I saw that the review article - [blog.skaplichniy.ru - Flags] (http://blog.skaplichniy.ru/all/flazhki/) - is no longer relevant =).

**Comment by freefelt** [comment]
Привет! Попробуйте сборку иэ [этого ответа](https://github.com/freefelt/YouType/issues/18#issuecomment-1367454085), пожалуйста. У некоторых пользователей действительно бывает такая проблема.

**Comment by grifoshPracticum** [comment]
Благодарю, сработало. 
Но программа просит обновиться - можно ли рассчитывать, что в будущем релизе это поправиться или уже не до этого проекта?

**Comment by freefelt** [comment]
Там можно нажать пропустить версию. Проблема исправлена в новой версии. Просто в ней очень много нового и доделать пока времени нет. Но в этом году она должна выйти точно. По крайней мере я на это надеюсь)

**Comment by grifoshPracticum** [comment]
Благодарю вас! Можно где-то поддержать разработку новой версии? :)

**Comment by freefelt** [comment]
В меню приложения есть нужный пункт, спасибо)
