### ISSUE TITLE
Отобразить иконку YouType в статус баре

### ISSUE THREAD

**Issue by MacLikbez** [freefelt/YouType#33]
Добрый день Александр. Спасибо за отличное приложение.

Обнаружил интересный баг. Если в настройках YouType выбрать скрыть иконку в статус баре, приложение предупреждает, что отобразить его можно вновь запустив приложение. Но это не работает. Приложение больше не появляется в статус баре и нельзя изменить настройки. Пробовал удалять приложение и связанные данные, даже через ваш скрипт удаления. Результат один — не могу получить доступ к иконке в статус баре и настройкам приложения.

Проверено на MacBook Air M1 (ventura 13.4)

**Comment by freefelt** [comment]
Добрый вечер!
Это не первое обращение по этой проблеме, но я ее никак пока не могу повторить, к сожалению.
Удаление файла настройки должно помочь.
~/Library/Preferences/com.AVKorotkov.YouType.plist

**Comment by MacLikbez** [comment]
Удаление этого файла не помогло. Но помогло удаление файлов .plist по пути ~/Library/Application Support/CrashReporter
файлы начинаются с Intervals. 
Далее перезагружаем компьютер и наконец сбрасываются настройки YouType.
Решение найдено пользователем сообщества МакЛикбез!

**Comment by freefelt** [comment]
А после удаления файла настроек перезагружался мак?

**Comment by MacLikbez** [comment]
> А после удаления файла настроек перезагружался мак?

Да, перезагружал. Но проблему решило только удаление файлов в CrashReporter

**Comment by freefelt** [comment]
Спасибо! Записал себе в список, буду разбираться.
