### ISSUE TITLE
Появление значка над нередактируемым текстом

### ISSUE THREAD

**Issue by jt3k** [freefelt/YouType#34]
Есть ли способ отображения флага только если курсор находится над полями ввода а не над любым текстом?

Текста вокруг много, и хотелось бы уменьшить эффект вязкости значка который перемещается вслед за курсором мыши )

p.s. Вроде бы в следующей версии макос приделают нативную такую же фичу, поэтому может и не стоит оно того). но я уверен, будет куча владельцев искусственно_состареных_аппле устройств которым такая программа будет полезна

**Comment by freefelt** [comment]
Привет! Есть такая функция, называется "Расширенный режим". Почитать про него можно [тут](https://bitbucket.org/avkorotkov/youtype/issues/11/).

**Comment by freefelt** [comment]
А можно попросить дать источник того, что в следующей версии макос приделают нативную такую же фичу, пожалуйста?

**Comment by jt3k** [comment]
Я видел это мельком в каком-то видео. Сейчас погуглил и нашёл [вот такое](https://www.iphones.ru/iNotes/35-novshestv-macos-sonoma-06-07-2023#:~:text=%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9%20%D0%B8%D0%BD%D0%B4%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%20%D1%8F%D0%B7%D1%8B%D0%BA%D0%B0%20%D0%B2%D0%B2%D0%BE%D0%B4%D0%B0) -- пункт 28

возможно это не совсем то же самое

**Comment by freefelt** [comment]
Спасибо! Действительно, функциональность схожая. У YouType тоже была задумка показывать индикатор рядом с текстовой кареткой, только вот система не дает местоположение каретки на экране. А для Windows версии такая функциональность есть. Может быть, в новой системе можно будет получать местоположение каретки на экране, тогда YouType будет все равно удобнее.
