### ISSUE TITLE
Flags missing!

### ISSUE THREAD

**Issue by hoseinpur** [freefelt/YouType#35]
Thank you for this app, it solved the problem of not showing the flags in the menu bar. However, I wanted to inform some issues and give suggestions.

- Missing flags: I switch between four languages: English/Persian/German/Turkish. I noticed that there is no flag for Iran(Persian language), I would also love to have this flag when I'm changing the input language. Could you please also include this?

- Flags stuck: I get that the point of this app is showing the current input flag in the type indicator while typing, but sometimes the flag got stuck at the last position of the type indicator, and sometimes it disappears. Would it be possible to fix this issue or maybe include an option in the menu to choose how and when to show the flags while typing? (see the image below, where the flag is shown!)

<img width="873" alt="image" src="https://github.com/freefelt/YouType/assets/8787772/309604fa-e3c9-44bb-8b4a-b4a8a820b94e">

**Comment by hoseinpur** [comment]
Please just ignore the second issue that I mentioned! sorry, it was already in the settings, I don't know why I didn't notice it before. But the first issue still remains! Thanks in advance for fixing it!

**Comment by freefelt** [comment]
Hi! Thanks for the feedback. All the flags that are in YouType are taken from previous versions of macOS and the Persian layout did not have a flag. Unfortunately, I cannot take responsibility in front of all users which flag should be used. In a future update, customization of indicators will be added in the form of a paid feature. You will be able to choose any flag/image yourself.
