### ISSUE TITLE
YouType for MacOsX Sonoma

### ISSUE THREAD

**Issue by MaximeZh** [freefelt/YouType#37]
Needhelp! I downloaded the Youtype program, thank you for it! Works great on MacBook Pro M1 +Sonoma. Now I have installed version -0.73(github), but I know that there is already version 1.1... But, unfortunately, I cannot download it, because the Apple Appstore does not allow users from Russia to download it. Please help me get a more recent version of Youtype& Thank you!

прошу о помощи! Скачал программу Youtype, спасибо вам за неё! Прекрасно работает на MacBook Pro M1 +Sonoma. Сейчас у меня установлена версия -0,73, но я знаю, что есть версия 1.1...Но я, к сожалению не могу её скачать, потому как AppleAppstore не позволяет её скачать пользователям из России. Прошу вас помочь мне получить более свежую версию Youtype& Спасибо!

[maxosmedia@gmail.com](mailto:maxosmedia@gmail.com)

**Comment by victordidenko** [comment]
How do you know there is a new version?
Also, what was changed?

**Comment by freefelt** [comment]
Hi! YouType 1.1 is an old version of the Mac AppStore written in Objective C. The YouType in this repository is a new version rewritten in Swift from scratch. The latest Swift version is 0.7.3. I'm sorry for the confusion.
