### ISSUE TITLE
Grey language block instead of lang flag

### ISSUE THREAD

**Issue by anton-evol** [freefelt/YouType#4]
Hi!
Is there any suggestions with issue like this:
<img width="59" alt="image" src="https://user-images.githubusercontent.com/94753594/168154802-19e59cfb-100a-49af-ba97-0af0c0a4d7ab.png">
At any language this is the only grey icon is showing.
Layouts used: USA int PC and RUS PC, if it matters.
Tried switch YouType options but unsuccessfully.
Thanks.

**Comment by freefelt** [comment]
Нашел проблему. Можно попробовать эту бету.
[YouType 0.3b1.zip](https://github.com/freefelt/YouType/files/8698893/YouType.0.3b1.zip)

**Comment by anton-evol** [comment]
Фантастика, всё заработало, спасибо!

**Comment by freefelt** [comment]
Это Вам спасибо)
https://github.com/freefelt/YouType/releases/tag/0.3
