### ISSUE TITLE
Хэлпер

### ISSUE THREAD

**Issue by MaximvsStorm** [freefelt/YouType#5]
А нужен ли теперь для корректной работы программы хелпер? И планируется ли новая Вин версия, я вот до сих пользуюсь старыми на Маке и Вин. Спасибо!

**Comment by freefelt** [comment]
Привет! Нет, для новой версии хелпер не нужен, вся его функциональность уже встроена в приложение. Он был нужен только для публикации приложения в стор. Выкладывать новую версию в стор пока не плнируется, слишком много там ограничений и условностей, да еще и платить надо $100 каждый год.
Я бы рекомендовал перейти на новую версию. Она лучше написана и более продуманная, не имеет костылей как старая версия. Так же, в нее встроена система обновлений. При новых версиях, появляется оповещение и обновиться можно одной кнопкой.
Windows версию я, к сожалению, развивать не планирую. Я уже сильно далек от Windows.

**Comment by MaximvsStorm** [comment]
Спасибо еще раз, Всё предельно понятно. Желаю всяческих успехов!
