### ISSUE TITLE
0.5 изчезает и падает

### ISSUE THREAD

**Issue by MaximvsStorm** [freefelt/YouType#6]
Здравствуйте! Система установлена 10.13.6. При переключении раскладки горячей клавишей (шифт) сначала исчезает значок (выбран флаг) в лотке. А потом программа падает при попытке переключения дальше. 0.4.1 при тех же действиях -  ничего не исчезает и не падает. И еще Значок флага у курсора и в лотке при переключении раскладки не совпадают, ну или значок в поле просто запаздывает в отображении. Еще установлен старый Пунтосвичер, который и отвечает за переключение раскладки шифтом. Может он и чудит.

**Comment by freefelt** [comment]
Привет! Спасибо за отчет. Пунтосвичер тут точно не причем, раскладка может меняться любым способом.
Попробуйте эту версию, пожалуйста. Есть ли там подобные проблемы?
[YouType0.5b1.zip](https://github.com/freefelt/YouType/files/8896536/YouType0.5b1.zip)

**Comment by MaximvsStorm** [comment]
Спасибо! Все работает. А то я уж опечалился что проблема на моей стороне.
