### ISSUE TITLE
Add option to remove flag from the cursor

### ISSUE THREAD

**Issue by MaximKukushkin** [freefelt/YouType#9]
It's a truly amazing application which fixes the most annoying and unreasonable change in MacOS 12.4. I'll definitely use it

However I only need to use it as a fix for the status bar (i.e., show flag instead text there). I don't really need any addition to my cursor.

Would it be possible to have a simple option in the settings to disable the input source indication following the cursor? (i.e., status bar icon only)

**Comment by freefelt** [comment]
Hi! Thanks for the feedback. The option will be in the next release.

**Comment by freefelt** [comment]
But I strongly advise you to try the indicators near the cursor. At first it seems unusual and disturbing, but after a couple of days you get used to it. And if you turn it off after that, then something seems to be missing. Especially in full-screen mode. This is very convenient when you don't have to constantly look in the upper right corner to find out the current keyboard layout.

**Comment by freefelt** [comment]
Implemented in YouType 0.7
